Add basic support for Fuchsia
google/cctz pull request #189
Opened 2021-06-08 22:55 UTC by kpozin

- Implement `FuchsiaZoneInfoSource` to read tzif2 files from their designated locations on Fuchsia systems.
- Implement calls to Fuchsia APIs in `local_time_zone()`.
- Disable a time conversion edge case that is unsupported on Fuchsia.

Bazel does not yet support Fuchsia configs, so these changes must be built and tested internally. See cl/374587662.

2021-06-08 22:58 UTC, kpozin commented
CC @filmil

2021-06-10 00:38 UTC, filmil reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/cctz/189)* status: all files reviewed, 7 unresolved discussions (waiting on @kpozin)

___
*[src/time_zone_info.cc, line 638 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnJJMa87SRckKPdvOV:-MbnJJMb4J1d2SkOEf3X:b-mpmjlu) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L638)):*
> ```cpp
>   // Returns a file pointer and the size of the file in bytes. If the file
>   // cannot be opened, returns a null file pointer and a size of 0.
>   static std::pair<FILE*, std::size_t> OpenZoneInfoFile(
> ```

Who closes the FILE*?
___
*[src/time_zone_info.cc, line 671 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnJeDcEtcxEiNXG338:-MbnJeDcEtcxEiNXG339:b-dntol5) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L671)):*
> ```cpp
> 
>   // Open the zoneinfo file.
>   auto fp_and_len = FileZoneInfoSource::OpenZoneInfoFile(path);
> ```

May wanna unpack with `std::tie` to avoid needing to use `.first` and `.second` which aren't too informative.  C++ version permitting.
___
*[src/time_zone_info.cc, line 679 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKD672iqSsmCE4OFQ:-MbnKD672iqSsmCE4OFR:bpoqqe0) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L679)):*
> ```cpp
> }
> 
> std::pair<FILE*, std::size_t> FileZoneInfoSource::OpenZoneInfoFile(
> ```

Is there any way to avoid returning a naked `FILE*` here?   It is all too easy to forget to close, or worse, leak the file if say an exception happens.
___
*[src/time_zone_info.cc, line 759 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKmjnBftXIW5I7NId:-MbnKmjnBftXIW5I7NIe:b79d43g) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L759)):*
> ```cpp
> class FuchsiaZoneInfoSource : public FileZoneInfoSource {
>  public:
>   static std::unique_ptr<ZoneInfoSource> Open(const std::string& name);
> ```

Document public API params?
___
*[src/time_zone_info.cc, line 763 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKbdE-rFNmQLi71rQ:-MbnKbdE-rFNmQLi71rR:b-ocxqx5) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L763)):*
> ```cpp
> 
>  private:
>   explicit FuchsiaZoneInfoSource(FILE* fp, std::size_t len, const char* vers)
> ```

I wonder, is there any way to use the C++ I/O here - `FILE*` gives me pause?
___
*[src/time_zone_lookup.cc, line 159 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnLJEq37JPpPzryijb:-MbnLJEq37JPpPzryijc:b2ws88d) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_lookup.cc#L159)):*
> ```cpp
>     std::unique_ptr<sys::ComponentContext> context =
>         sys::ComponentContext::Create();
>     fuchsia::intl::PropertyProviderPtr intl_provider =
> ```

Would a `SyncPtr` be simpler here, by any chance? You are effectively synchronizing on the call returning.
___
*[src/time_zone_lookup_test.cc, line 1026 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnLYhD2GL118qapFPP:-MbnLYhD2GL118qapFPQ:bb69o2h) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_lookup_test.cc#L1026)):*
> ```cpp
>     tp = convert(civil_second(min_tm_year, 1, 1, 0, 0, 0), cut);
> #if defined(__Fuchsia__)
>     // Fuchsia's gmtime_r() fails on extreme negative tm_year values.
> ```

#til


<!-- Sent from Reviewable.io -->

2021-06-10 04:25 UTC, devbww requested changes
> Bazel does not yet support Fuchsia configs, so these changes must be
> tested internally. See cl/374587662.

We probably shouldn't be mentioning "internally" here, or giving links to inaccessible information.  This is an open-source project.

Not being able to build/test this code in CCTZ comes close to a fatal flaw too.  There is no way I can guarantee that future changes won't break Fuchsia if we can't support something like a Kokoro build here.  The same thing is currently true for Android, but see the discussion about conditional compilation.

> *[Reviewable](https://reviewable.io/reviews/google/cctz/189#-:-Mbnn46sAjaq_6tFGe2A:b5knka2)* status: all files reviewed, 15 unresolved discussions (waiting on @filmil and @kpozin)

___
*[src/time_zone_info.cc, line 638 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnJJMa87SRckKPdvOV:-Mbnoa-v5tpc5yR0o5k6:b-sijcdm) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L638)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Who closes the FILE*?
</blockquote></details>

The `FileZoneInfoSource` dtor, via the `FileZoneInfoSource::fp_` dtor.  But, see the discussion below.
___
*[src/time_zone_info.cc, line 679 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKD672iqSsmCE4OFQ:-Mbnq5aLAL2TWlNFqXd_:b-6af4pk) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L679)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Is there any way to avoid returning a naked `FILE*` here?   It is all too easy to forget to close, or worse, leak the file if say an exception happens.
</blockquote></details>

Previously the disposition of the `FILE*` was much clearer ... straight from the result of `FOpen()` to the `FileZoneInfoSource` ctor.  The imposition of the `pair` adds an extra layer.

And the `pair` is pretty much what a `FileZoneInfoSource` is, together with the closing property you ask about.  So, I would think that there is someway to avoid the `pair` altogether.

Perhaps one simple approach is to factor out a `std::size_t FSize(FILE*)` helper.  Then `FileZoneInfoSource::Open()` and `FuchsiaZoneInfoSource::Open()` can both just call `FOpen()` and `FSize()` independently, and there is no need for a `pair` at all.

That would also get rid of the `OpenZoneInfoFile()` function, which actually had nothing to do with "zoneinfo".
___
*[src/time_zone_info.cc, line 749 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo2EHP8ICaS6ci0WBd:-Mbo2EHP8ICaS6ci0WBe:b608l7z) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L749)):*
> ```cpp
> 
> #if defined(__Fuchsia__)
> // An info source for using cctz inside Fuchsia components. This attempts to
> ```

I would suggest `s/info/zoneinfo/`.  We don't use "info" anywhere else.

I'd also suggest rewording to avoid "using cctz".  This is all about using cctz.  (If we have to refer to the package in other documentation we tend to say "CCTZ".)
___
*[src/time_zone_info.cc, line 759 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKmjnBftXIW5I7NId:-Mbnw37d8rkViKaiqbXo:b4hpnex) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L759)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

Document public API params?
</blockquote></details>

This isn't public.  The inter-module documentation is on `TimeZoneIf::Load()`, and the actual public documentation is on `cctz::load_time_zone()`.
___
*[src/time_zone_info.cc, line 769 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbny_AD4E4LBpjw8pbd:-Mbny_AD4E4LBpjw8pbe:bm729fr) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L769)):*
> ```cpp
> };
> 
> // Reads the contents of the file as ASCII. Returns an empty string on error.
> ```

This doesn't seem to have anything to do with ASCII.
___
*[src/time_zone_info.cc, line 796 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnzTWUBXZ4qlQ4yV29:-MbnzTWUBXZ4qlQ4yV2A:b-ep93wc) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L796)):*
> ```cpp
>   // Use of the "file:" prefix is intended for testing purposes only.
>   const std::size_t pos = (name.compare(0, 5, "file:") == 0) ? 5 : 0;
>   const bool is_test_path = (pos != name.size() && name[pos] == '/');
> ```

I'm not sure what "test" means, but `is_test_path` seems better as `is_absolute_path`.  Then not adding a prefix nor a format prefix to an absolute path makes more sense.
___
*[src/time_zone_info.cc, line 816 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnypCPE25Fbhc9TDkF:-MbnypCPE25Fbhc9TDkG:bqd9m99) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L816)):*
> ```cpp
>     std::string version_path = tzdata_dir;
>     version_path += kVersionFileName;
>     std::string version_str = ReadFileAsString(version_path);
> ```

Does the "revision.txt" file have a terminating newline?  If so, you'll want to omit it from `version_str`.  (You may also want to be defensive about data beyond one line.)
___
*[src/time_zone_info.cc, line 839 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo0U1y7vfJJuuQl4jz:-Mbo0SKz0MEktovJyWH7:bxzdaqz) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L839)):*
> ```cpp
>   auto zip = cctz_extension::zone_info_source_factory(
>       name, [](const std::string& n) -> std::unique_ptr<ZoneInfoSource> {
> #if defined(__Fuchsia__)
> ```

I would suggest that every platform should support finding zoneinfo files in `${TZDIR}`.  That is, that `FileZoneInfoSource::Open() is unconditionally first.

We can discuss whether anything after that needs to be conditional (at the cost of some failed opens).  Notice that this module supports Android, but doesn't conditionally compile anything for Android.  This helps with avoiding Android breakages when we don't build/test for it.
___
*[src/time_zone_lookup.cc, line 151 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo7Oxs465hUJOoTEhK:-Mbo7Oxs465hUJOoTEhL:bajmn10) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_lookup.cc#L151)):*
> ```cpp
> #endif
> #if defined(__Fuchsia__)
>   // Note: Declared outside of unnamed scope to avoid early destruction.
> ```

I'd drop this note.  Everything is declared where it needs to be.
___
*[src/time_zone_lookup.cc, line 154 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo9K5JBFxjKPGG94Pm:-Mbo9K5JBFxjKPGG94Pn:bopvji0) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_lookup.cc#L154)):*
> ```cpp
>   std::string primary_tz;
>   {
>     const zx::duration kTimeout = zx::msec(500);
> ```

I don't understand your architecture of course, but is timing out a real possibility?  Perhaps this is related to Filip's `SyncPtr` question.
___
*[src/time_zone_lookup.cc, line 159 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo7nvDCDgii1w2OJnm:-Mbo7nvDCDgii1w2OJnn:b-7t4fp1) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_lookup.cc#L159)):*
> ```cpp
>     std::unique_ptr<sys::ComponentContext> context =
>         sys::ComponentContext::Create();
>     fuchsia::intl::PropertyProviderPtr intl_provider =
> ```

auto?
___
*[src/time_zone_lookup_test.cc, line 1026 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnLYhD2GL118qapFPP:-Mbo8Ico7lDbrhYEWZOM:b-8qqn5q) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_lookup_test.cc#L1026)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</ [...]

2021-06-10 07:08 UTC, devbww reviewed
> *[Reviewable](https://reviewable.io/reviews/google/cctz/189)* status: all files reviewed, 15 unresolved discussions (waiting on @filmil and @kpozin)

___
*[src/time_zone_info.cc, line 679 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKD672iqSsmCE4OFQ:-MbogoGZ5eia57vCv5M2:bdj907u) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L679)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Previously the disposition of the `FILE*` was much clearer ... straight from the result of `FOpen()` to the `FileZoneInfoSource` ctor.  The imposition of the `pair` adds an extra layer.

And the `pair` is pretty much what a `FileZoneInfoSource` is, together with the closing property you ask about.  So, I would think that there is someway to avoid the `pair` altogether.

Perhaps one simple approach is to factor out a `std::size_t FSize(FILE*)` helper.  Then `FileZoneInfoSource::Open()` and `FuchsiaZoneInfoSource::Open()` can both just call `FOpen()` and `FSize()` independently, and there is no need for a `pair` at all.

That would also get rid of the `OpenZoneInfoFile()` function, which actually had nothing to do with "zoneinfo".
</blockquote></details>

That said, there is actually no need to predetermine the length of the file.  The `len` argument to the `FileZoneInfoSource` ctor can be omitted when the file is simply TZif.  The `len` argument is only needed in cases like `AndroidZoneInfoSource`, where the TZif data has been encapsulated inside another file.

[That begs the question of why `FileZoneInfoSource::Open()` bothers to specify `len`, but that is either an historical artifact or a refactoring error.  I'll remove it.]

The bottom line is that `FuchsiaZoneInfoSource::Open()` can just use `FOpen()` alone (if I understand your file layout).


<!-- Sent from Reviewable.io -->

2021-06-11 01:02 UTC, kpozin reviewed
We're willing to live with the possibility of being broken upstream and submitting retroactive fixes for now; Fuchsia is already in this position with a few other open-source libraries.

I removed the conditional compilation where possible, but we're stuck with it in `time_zone_lookup.cc`, which requires Fuchsia-only libraries.

> *[Reviewable](https://reviewable.io/reviews/google/cctz/189#-:-MbsI2t88SKULiIyeZzX:b-5x7058)* status: 0 of 3 files reviewed, 15 unresolved discussions (waiting on @devbww and @filmil)

___
*[src/time_zone_info.cc, line 638 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnJJMa87SRckKPdvOV:-MbsIYHl-vq_o7GIbb65:bb6sh2i) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L638)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

The `FileZoneInfoSource` dtor, via the `FileZoneInfoSource::fp_` dtor.  But, see the discussion below.
</blockquote></details>

Ack.
___
*[src/time_zone_info.cc, line 671 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnJeDcEtcxEiNXG338:-MbsI_Jt98DCYzgl3ONM:bhufgfa) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L671)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

May wanna unpack with `std::tie` to avoid needing to use `.first` and `.second` which aren't too informative.  C++ version permitting.
</blockquote></details>

I switched to @devbww's suggested refactoring.
___
*[src/time_zone_info.cc, line 679 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKD672iqSsmCE4OFQ:-MbrHmut31UUfSzcgYS5:b7ucoll) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L679)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

That said, there is actually no need to predetermine the length of the file.  The `len` argument to the `FileZoneInfoSource` ctor can be omitted when the file is simply TZif.  The `len` argument is only needed in cases like `AndroidZoneInfoSource`, where the TZif data has been encapsulated inside another file.

[That begs the question of why `FileZoneInfoSource::Open()` bothers to specify `len`, but that is either an historical artifact or a refactoring error.  I'll remove it.]

The bottom line is that `FuchsiaZoneInfoSource::Open()` can just use `FOpen()` alone (if I understand your file layout).
</blockquote></details>

`std::size_t FSize(FILE*)` sounds like the best option. I'll keep `FileZoneInfoSource` as the base class of `FuchsiaZoneInfoSource` for now, so `len` is still needed for the constructor.
___
*[src/time_zone_info.cc, line 749 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo2EHP8ICaS6ci0WBd:-MbrJFAeDNQXDHYg4Y6e:b-896fix) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L749)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I would suggest `s/info/zoneinfo/`.  We don't use "info" anywhere else.

I'd also suggest rewording to avoid "using cctz".  This is all about using cctz.  (If we have to refer to the package in other documentation we tend to say "CCTZ".)
</blockquote></details>

Done.
___
*[src/time_zone_info.cc, line 759 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKmjnBftXIW5I7NId:-MbrJG-G0xb2sZyoxDNU:b2nhb2c) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L759)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

This isn't public.  The inter-module documentation is on `TimeZoneIf::Load()`, and the actual public documentation is on `cctz::load_time_zone()`.
</blockquote></details>

Ack
___
*[src/time_zone_info.cc, line 763 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKbdE-rFNmQLi71rQ:-MbrJLzU3MgzUNPonp6C:b2nhb2c) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L763)):*
<details><summary><i>Previously, filmil (Filip Filmar) wrote…</i></summary><blockquote>

I wonder, is there any way to use the C++ I/O here - `FILE*` gives me pause?
</blockquote></details>

Ack
___
*[src/time_zone_info.cc, line 769 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbny_AD4E4LBpjw8pbd:-MbrEdNJ4cUt2YPHpiT-:bjfzbd7) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L769)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

This doesn't seem to have anything to do with ASCII.
</blockquote></details>

Corrected comment.
___
*[src/time_zone_info.cc, line 796 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnzTWUBXZ4qlQ4yV29:-MbrFu_-5s8mqX7VZJiS:b-896fix) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L796)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I'm not sure what "test" means, but `is_test_path` seems better as `is_absolute_path`.  Then not adding a prefix nor a format prefix to an absolute path makes more sense.
</blockquote></details>

Done.
___
*[src/time_zone_info.cc, line 816 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnypCPE25Fbhc9TDkF:-MbrJkCAC_HMGmSSwvAj:b-3k5z4o) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L816)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Does the "revision.txt" file have a terminating newline?  If so, you'll want to omit it from `version_str`.  (You may also want to be defensive about data beyond one line.)
</blockquote></details>

Done. No newlines in the format, but I'll use the defensive approach.
___
*[src/time_zone_info.cc, line 839 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo0U1y7vfJJuuQl4jz:-MbrMpWKAtN-llqbvA_E:b-hasdlw) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L839)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I would suggest that every platform should support finding zoneinfo files in `${TZDIR}`.  That is, that `FileZoneInfoSource::Open() is unconditionally first.

We can discuss whether anything after that needs to be conditional (at the cost of some failed opens).  Notice that this module supports Android, but doesn't conditionally compile anything for Android.  This helps with avoiding Android breakages when we don't build/test for it.
</blockquote></details>

What if we added a `const bool kIsFuchsia` based on `defined(__Fuchsia__`? Then the compilation will be unconditional but we won't make extraneous calls at runtime.
___
*[src/time_zone_lookup.cc, line 151 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo7Oxs465hUJOoTEhK:-MbrNOW6CHdH-nFnS8ZV:b-896fix) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_lookup.cc#L151)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I'd drop this note.  Everything is declared where it needs to be.
</blockquote></details>

Done.
___
*[src/time_zone_lookup.cc, line 154 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo9K5JBFxjKPGG94Pm:-MbrNPNz1XcKeV4lDD3X:bfjl9ka) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_lookup.cc#L154)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I don't understand your architecture of course, but is timing out a real possibility?  Perhaps this is related to Filip's `SyncPtr` question.
</blockquote></details>

Added an explanatory comment to the code.
Yes, there are some failure states whe [...]

2021-06-11 03:04 UTC, devbww requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/cctz/189)* status: all files reviewed, 9 unresolved discussions (waiting on @filmil and @kpozin)

___
*[src/time_zone_info.cc, line 679 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKD672iqSsmCE4OFQ:-Mbt--KO21tIvTmjNIjL:b-q64pkt) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L679)):*
<details><summary><i>Previously, kpozin (Konstantin Pozin) wrote…</i></summary><blockquote>

`std::size_t FSize(FILE*)` sounds like the best option. I'll keep `FileZoneInfoSource` as the base class of `FuchsiaZoneInfoSource` for now, so `len` is still needed for the constructor.
</blockquote></details>

See above.
___
*[src/time_zone_info.cc, line 839 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo0U1y7vfJJuuQl4jz:-Mbt-WGj6yFoZo0hbffM:b-cfpwt3) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L839)):*
<details><summary><i>Previously, kpozin (Konstantin Pozin) wrote…</i></summary><blockquote>

What if we added a `const bool kIsFuchsia` based on `defined(__Fuchsia__`? Then the compilation will be unconditional but we won't make extraneous calls at runtime.
</blockquote></details>

That's fine I guess, although I'm not sure I would worry about the failing opens in the non-Fuchsia cases.

However, I still think the `FileZoneInfoSource::Open()` should always come first.
___
*[src/time_zone_info.cc, line 625 at r2](https://reviewable.io/reviews/google/cctz/189#-Mbsyzu-DUF0P04AgxSK:-Mbsyzu-DUF0P04AgxSL:b-r0zi1y) ([raw file](https://github.com/google/cctz/blob/448c5b1f940ef98411df6135197c1c02397a51d4/src/time_zone_info.cc#L625)):*
> ```cpp
>   }
>   return length;
> }
> ```

To clarify what I was suggesting, `FSize()` is not actually needed.  In the two cases it is currently used, the second argument to the `FileZoneInfoSource` ctor can instead be omitted (giving the parameter its default value, which will allow reading to EOF).

That is, delete this function, remove its use from `FileZoneInfoSource::Open()`, and remove `len` from your new `FuchsiaZoneInfoSource` ctor.


<!-- Sent from Reviewable.io -->

2021-06-11 18:46 UTC, devbww requested changes
> *[Reviewable](https://reviewable.io/reviews/google/cctz/189)* status: all files reviewed, 9 unresolved discussions (waiting on @filmil and @kpozin)

___
*[src/time_zone_info.cc, line 625 at r2](https://reviewable.io/reviews/google/cctz/189#-Mbsyzu-DUF0P04AgxSK:-MbwNGPb3npUAIb1gWXP:b-5gns5v) ([raw file](https://github.com/google/cctz/blob/448c5b1f940ef98411df6135197c1c02397a51d4/src/time_zone_info.cc#L625)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

To clarify what I was suggesting, `FSize()` is not actually needed.  In the two cases it is currently used, the second argument to the `FileZoneInfoSource` ctor can instead be omitted (giving the parameter its default value, which will allow reading to EOF).

That is, delete this function, remove its use from `FileZoneInfoSource::Open()`, and remove `len` from your new `FuchsiaZoneInfoSource` ctor.
</blockquote></details>

I do have a pending edit to clean the file-size stuff up independently, if you would like me to get that in first.


<!-- Sent from Reviewable.io -->

2021-06-11 19:10 UTC, kpozin reviewed
> *[Reviewable](https://reviewable.io/reviews/google/cctz/189)* status: 2 of 3 files reviewed, 9 unresolved discussions (waiting on @devbww and @filmil)

___
*[src/time_zone_info.cc, line 679 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnKD672iqSsmCE4OFQ:-MbwDJPt1Wf48o0GJY5t:b-896fix) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L679)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[src/time_zone_info.cc, line 839 at r1](https://reviewable.io/reviews/google/cctz/189#-Mbo0U1y7vfJJuuQl4jz:-MbwPfxzEFJ0G_6kTyNP:bjwgxfk) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_info.cc#L839)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

That's fine I guess, although I'm not sure I would worry about the failing opens in the non-Fuchsia cases.

However, I still think the `FileZoneInfoSource::Open()` should always come first.
</blockquote></details>

Done. Also added a `const bool kIsAndroid`.
___
*[src/time_zone_info.cc, line 625 at r2](https://reviewable.io/reviews/google/cctz/189#-Mbsyzu-DUF0P04AgxSK:-MbwDDMYBEdrYneAZiLI:bn203y8) ([raw file](https://github.com/google/cctz/blob/448c5b1f940ef98411df6135197c1c02397a51d4/src/time_zone_info.cc#L625)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I do have a pending edit to clean the file-size stuff up independently, if you would like me to get that in first.
</blockquote></details>

Done. Sorry for my misunderstanding.


<!-- Sent from Reviewable.io -->

2021-06-11 20:22 UTC, devbww approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/cctz/189)* status: all files reviewed, 7 unresolved discussions (waiting on @filmil)



<!-- Sent from Reviewable.io -->

2021-06-11 20:26 UTC, filmil reviewed
> *[Reviewable](https://reviewable.io/reviews/google/cctz/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kpozin)

___
*[src/time_zone_lookup.cc, line 159 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnLJEq37JPpPzryijb:-Mbwjwa954mzdFQffZRE:bxumkec) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_lookup.cc#L159)):*
<details><summary><i>Previously, kpozin (Konstantin Pozin) wrote…</i></summary><blockquote>

(See above. The sync API doesn't allow timeouts.)
</blockquote></details>

OK

Separately, I wonder if we can do something about the need to watch for a timeout.
___
*[src/time_zone_lookup_test.cc, line 1026 at r1](https://reviewable.io/reviews/google/cctz/189#-MbnLYhD2GL118qapFPP:-MbwkBqy5az4hQZN5cTV:bechevw) ([raw file](https://github.com/google/cctz/blob/e8e74cdbf8c0d108f390cf9a55e55a230f601b35/src/time_zone_lookup_test.cc#L1026)):*
<details><summary><i>Previously, kpozin (Konstantin Pozin) wrote…</i></summary><blockquote>

We're using musl. I just responded on #187 with a rough analysis of the bug in their `gmtime_r` implementation, but fixing musl's date calculations is a bit out of my scope for now :)
</blockquote></details>

OK

Closing this comment, I'm OK with what kpozin@ said.  Feel free to reopen if you think otherwise.


<!-- Sent from Reviewable.io -->

2021-06-11 22:23 UTC, kpozin commented
I think we're all set. Please merge whenever convenient.

2021-06-11 23:18 UTC, merged